version: '3.4'

services:
  csdsshop:
    image: ${DOCKER_REGISTRY-}csdsshop
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - minio
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /d/minio:/data
    environment:
    ## TODO: it is very bad to store secrets in clear text
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: D@nceL1fE
    command: server --console-address ":9001" /data

  configure-minio:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 admin D@nceL1fE;
      /usr/bin/mc mb --ignore-existing minio/images;
      /usr/bin/mc anonymous set download minio/images;
      exit 0;
      "